// This file was autogenerated by calcdeps.py
goog.addDependency('../sketch/historystack.js', ['sketch.HistoryStack'], []);
goog.addDependency('../sketch/canvas.js', ['sketch.Canvas'], ['sketch.HistoryStack', 'goog.dom', 'goog.graphics', 'goog.ui.Component']);
goog.addDependency('../sketch/drawaction.js', ['sketch.DrawAction'], ['sketch.Action', 'goog.graphics']);
goog.addDependency('../sketch/action.js', ['sketch.Action'], []);

